name: Corporator_Mobile_App
description: A new Flutter project.

version: 1.0.2
environment:
  sdk: '>=2.7.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rounded_date_picker: 1.0.4
  image_picker: ^0.7.4
  flutter_svg: ^0.21.0+1
  bottom_navy_bar: ^6.0.0
  multi_image_picker: ^4.8.0 
  google_maps_flutter: ^2.0.5
  permission_handler: ^8.0.0+2
  geocoder: ^0.2.1
  intl:
  dropdown_below: ^0.0.7
  simple_autocomplete_formfield: ^0.3.0
  autocomplete_textfield: ^1.7.3
  share: ^2.0.1
  video_player: ^2.1.1
  chewie: ^1.0.0
  url_launcher: ^6.0.4
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icons/calendar.svg
    - assets/icons/text-font.svg
    - assets/icons/share.svg
    - assets/icons/alert-octagon.svg
    - assets/icons/home.svg
    - assets/icons/user.svg


  fonts:
    - family: ProductSans
      fonts:

        - asset: assets/fonts/Product_Sans_Regular.ttf
        - asset: assets/fonts/Product_Sans_Bold.ttf
